In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [9]:
a=np.array ([30,24,90])

In [10]:
a

array([30, 24, 90])

In [22]:
#creating numpy with 5 arrays
a=np.array([6,7,8,7,5])

In [23]:
a

array([6, 7, 8, 7, 5])

In [18]:
#creating numpy with 10 arrays
b=np.array([2,3,4,5,6,7,8,9,10,1])

In [19]:
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10,  1])

In [20]:
b.shape

(10,)

In [21]:
b.ndim

1

In [24]:
a.shape

(5,)

In [25]:
a.ndim

1

In [26]:
c=np.array([[1,2],[3,4]])

In [27]:
c

array([[1, 2],
       [3, 4]])

In [28]:
c.shape

(2, 2)

In [29]:
c.ndim

2

In [30]:
d=np.array([[3,4,5],[1,5,2]])

In [31]:
d

array([[3, 4, 5],
       [1, 5, 2]])

In [32]:
d.shape

(2, 3)

In [33]:
d.ndim

2

In [34]:
d.dtype

dtype('int64')

In [35]:
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10,  1])

In [36]:
b[2]  #indexing

np.int64(4)

In [37]:
b[2:6]  #slicing

array([4, 5, 6, 7])

In [40]:
x=np.array([1,2,3,4,5])

In [41]:
y=np.array([9,8,7,6,8])

In [42]:
x+y #addition


array([10, 10, 10, 10, 13])

In [43]:
x-y #substraction

array([-8, -6, -4, -2, -3])

In [44]:
x*y #multiplication

array([ 9, 16, 21, 24, 40])

In [45]:
x/y #division

array([0.11111111, 0.25      , 0.42857143, 0.66666667, 0.625     ])

In [46]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [47]:
np.exp(x) #exponential value:2.178

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [53]:
2.718**2

7.387524

In [49]:
2.718**5

148.33623849186557

In [51]:
2.718**4

54.575510850575995

In [52]:
2.718**3

20.079290231999998

In [61]:
z=np.arange(12) #arange

In [62]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
z.ndim

1

In [64]:
z.shape

(12,)

In [65]:
z.dtype

dtype('int64')

In [66]:
w=z.reshape((3,4))  #reshape

In [67]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
w.shape

(3, 4)

In [69]:
w.ndim

2

In [70]:
w.dtype

dtype('int64')